### ISSUE TITLE
WP-scribbles theme -- product page has components displaying in wrong place on page

### ISSUE THREAD

**Issue by mrsbmw** [LiftUX/scribbles-theme#10]
Creating a site with WP Scribbles Theme.  Added a Products page.  The Hero Background and Header Image are displayed at the very top of the page vice below the menu as they should be.   My other pages display these items in the correct place.  This is the way the canned Products Page was loaded, not as a result of any customizing done by me
![correct display home page](https://cloud.githubusercontent.com/assets/24994874/21753979/716d2eb0-d5c5-11e6-9028-bdc9030c1da3.png)
![incorrect display - products page](https://cloud.githubusercontent.com/assets/24994874/21753980/716d6bdc-d5c5-11e6-85f8-8407baaffdc7.png)

website is published but not advertised, as it is still not complete.   www.connectingquilters.net

**Comment by EvanHerman** [comment]
Hi there @mrsbmw ,

At the moment the themes are not fully compatible with WooCommerce.

We are in the process of building in support for WooCommerce into Primer and its child themes. When that patch is released, the page templates will blend seamlessly with the current layout that you have on your pages. The patch should be out in the coming weeks.

In the meantime have you taken a look at the process for integrating a theme with WooCommerce by customizing the templates?

https://docs.woocommerce.com/document/template-structure/

You can customize any of the templates included with WooCommerce so that they blend seamlessly with the theme you are running.

As a preview of the upcoming patch, here is the WooCommerce shop page running on the Scribbles theme:

<img src="https://cldup.com/-2RE8JNSg2.png" width="85%" />
